version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - ./baseball_stats.db:/baseball_stats.db
    environment:
      MB_DB_FILE: /baseball_stats.db
      MB_DB_TYPE: sqlite